# Generated by Django 3.2 on 2021-12-08 12:46

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(blank=True, max_length=500)),
                ('category_image', models.ImageField(upload_to='media/category')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='cushion',
            fields=[
                ('cushion_id', models.AutoField(primary_key=True, serialize=False)),
                ('cushion_size', models.CharField(blank=True, max_length=500)),
                ('cushion_price', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='fabric_color',
            fields=[
                ('fabric_id', models.AutoField(primary_key=True, serialize=False)),
                ('color_name', models.CharField(blank=True, max_length=500)),
                ('color_image', models.ImageField(upload_to='media/fabric')),
            ],
        ),
        migrations.CreateModel(
            name='frame_color',
            fields=[
                ('frame_id', models.AutoField(primary_key=True, serialize=False)),
                ('color_name', models.CharField(blank=True, max_length=500)),
                ('color_image', models.ImageField(upload_to='media/frame')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(blank=True, max_length=500)),
                ('SKU', models.CharField(blank=True, max_length=500)),
                ('product_price', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('warrenty_terms', models.TextField(blank=True, max_length=1000)),
                ('return_cancellation', models.CharField(blank=True, max_length=500)),
                ('length', models.CharField(blank=True, max_length=500)),
                ('width', models.CharField(blank=True, max_length=500)),
                ('height', models.CharField(blank=True, max_length=500)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lumes_craft.category')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, max_length=500)),
                ('email', models.EmailField(blank=True, max_length=500)),
                ('phone', models.CharField(blank=True, max_length=500)),
                ('alternate_phone', models.CharField(blank=True, max_length=500)),
                ('address', models.TextField(blank=True, max_length=500)),
                ('gstin', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='wicker_color',
            fields=[
                ('wicker_id', models.AutoField(primary_key=True, serialize=False)),
                ('color_name', models.CharField(blank=True, max_length=500)),
                ('color_image', models.ImageField(upload_to='media/wicker')),
            ],
        ),
        migrations.CreateModel(
            name='quotation',
            fields=[
                ('quotation_id', models.AutoField(primary_key=True, serialize=False)),
                ('details', jsonfield.fields.JSONField(default=dict)),
                ('invoice', models.FileField(blank=True, upload_to='media/invoice')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lumes_craft.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='product_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to='media/products_images')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lumes_craft.product')),
            ],
        ),
    ]
