# Generated by Django 3.2 on 2021-11-19 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lumes_craft', '0002_alter_category_update_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(blank=True, max_length=500)),
                ('SKU', models.CharField(blank=True, max_length=500)),
                ('product_price', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('warrenty_terms', models.TextField(blank=True, max_length=1000)),
                ('return_cancellation', models.CharField(blank=True, max_length=500)),
                ('dimensions', models.CharField(blank=True, max_length=500)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lumes_craft.category')),
            ],
        ),
    ]
