# Generated by Django 3.2 on 2021-11-19 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lumes_craft', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to='home/rajnish/Music/lumes_craft/lumescraft/media')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lumes_craft.product')),
            ],
        ),
    ]
