# Generated by Django 3.2 on 2021-11-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumes_craft', '0005_fabric_color_frame_color_wicker_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, max_length=500)),
                ('email', models.EmailField(blank=True, max_length=500)),
                ('phone', models.CharField(blank=True, max_length=500)),
                ('alternate_phone', models.CharField(blank=True, max_length=500)),
                ('address', models.TextField(blank=True, max_length=500)),
            ],
        ),
    ]
